-- Create profiles table for user metadata
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  first_name text not null,
  last_name text not null,
  mobile_number text,
  created_at timestamptz not null default now()
);

-- Enable Row Level Security
alter table public.profiles enable row level security;

create policy "Users can view their own profile"
  on public.profiles for select
  using (auth.uid() = id);

create policy "Users can update their own profile"
  on public.profiles for update
  using (auth.uid() = id);

create policy "Users can insert their own profile"
  on public.profiles for insert
  with check (auth.uid() = id);

-- Complaint table
create table if not exists public.complaints (
  id bigint generated by default as identity primary key,
  student_name text not null,
  title text not null,
  category text not null,
  priority text not null default 'Medium',
  status text not null default 'Submitted',
  description text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  resolution_note text
);

alter table public.complaints enable row level security;

create policy "Anyone can view complaints"
  on public.complaints for select
  using (true);

create policy "Authenticated users can insert complaints"
  on public.complaints for insert
  with check (auth.role() = 'authenticated');

create policy "Authenticated users can update complaints"
  on public.complaints for update
  using (auth.role() = 'authenticated');

create trigger set_updated_at
  before update on public.complaints
  for each row
  execute procedure public.set_updated_at();

-- Optional helper function for updated_at
create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;
